name: Build and Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create keystore file
      run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > $GITHUB_WORKSPACE/vergissnix.keystore

    - name: Build APK with Gradle
      env:
        ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
      run: ./gradlew publishApk --no-daemon
        -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/vergissnix.keystore
        -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }}
        -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}
        -Pandroid.injected.signing.v2-enabled=true
      
    - name: Cleanup
      run: rm $GITHUB_WORKSPACE/vergissnix.keystore
