name: Build and Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create keystore file
      run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > $GITHUB_WORKSPACE/vergissnix.keystore

    - name: Build APK with Gradle
      run: ./gradlew assembleRelease
        -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/vergissnix.keystore
        -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }}
        -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}
        -Pandroid.injected.signing.v2-enabled=true
      
    - name: Cleanup
      run: rm $GITHUB_WORKSPACE/vergissnix.keystore

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app/release/app-release.apk
        asset_name: vergissnix-${{ github.ref }}.apk
        tag: ${{ github.ref }}
        overwrite: true
        body: "Release ${{ github.ref }}"
